apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: b1f2bp9jc-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: b1f2bp9jc-python 
  name: b1f2bp9jc-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: b1f2bp9jc-python 
