apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: b1f2bp9jc-python 
  janus-idp.io/tekton: b1f2bp9jc-python
  backstage.io/kubernetes-id: b1f2bp9jc-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: b1f2bp9jc-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml